version: '3.8'

services:
  web:
    build: .
    container_name: ride_app
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --log-level debug RideShare.wsgi:application  # Adjust this for fewer workers
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Persist SQLite database
    expose:
      - "8000"  # Use expose instead of ports since Nginx proxies it
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - web

networks:
  webnet:
    driver: bridge
