version: '3.8'

services:
  web:
    build: .
    container_name: ride_app
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --log-level debug RideShare.wsgi:application
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt  # Store SSL certificates
      - ./certbot/www:/var/www/certbot  # For Certbot HTTP-01 challenge
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS port
    networks:
      - webnet
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  webnet:
    driver: bridge
